In [2]:
!pip install requests pandas tqdm --quiet

import re
import time
import requests
import pandas as pd
from tqdm.notebook import tqdm
from datetime import datetime, timedelta, timezone

# =========================================================
# CONFIG
# =========================================================
SUBREDDIT = "askscience"
START_DATE = "2025-10-06"
END_DATE   = "2025-12-28"

# Week-balanced collection
TARGET_CLEAN_PER_WEEK = 250   # 12 weeks -> about 3000 clean comments if available
LABEL_PER_WEEK = 25           # balanced labeling file across weeks
OVERLAP_LABEL_N = 100         # overlap set for two annotators

# Request settings
COMMENT_PAGE_LIMIT = 100
POST_PAGE_LIMIT = 100
SLEEP_SEC = 0.45
MAX_RETRIES = 5
HEADERS = {"User-Agent": "Mozilla/5.0 academicRedditStudy/5.0"}

# Endpoints
BASE_COMMENTS = "https://arctic-shift.photon-reddit.com/api/comments/search"
BASE_POSTS    = "https://arctic-shift.photon-reddit.com/api/posts/search"

# Cleaning controls
MIN_TEMPLATE_WORDS = 12
AUTOMOD_RE = re.compile(r"^automoderator$", re.IGNORECASE)
MODTEAM_RE = re.compile(r"(?:^|[-_ ])modteam(?:$|[-_ ])", re.IGNORECASE)

# =========================================================
# HELPERS
# =========================================================
def to_ts(date_str: str) -> int:
    return int(datetime.strptime(date_str, "%Y-%m-%d").replace(tzinfo=timezone.utc).timestamp())

def ts_to_iso(ts: int) -> str:
    return datetime.fromtimestamp(int(ts), tz=timezone.utc).isoformat()

def normalize_text(x):
    if x is None:
        return ""
    return str(x).strip()

def build_week_ranges(start_date: str, end_date: str):
    start_ts = to_ts(start_date)
    end_ts = to_ts(end_date) + 86399
    windows = []

    cursor = start_ts
    i = 1
    while cursor <= end_ts:
        win_end = min(cursor + 7 * 86400 - 1, end_ts)
        windows.append({
            "week_idx": i,
            "after_ts": int(cursor),
            "before_ts": int(win_end),
            "week_label": f"W{i:02d}_{ts_to_iso(cursor)[:10]}_to_{ts_to_iso(win_end)[:10]}",
            "window_start_utc": ts_to_iso(cursor),
            "window_end_utc": ts_to_iso(win_end),
        })
        cursor = win_end + 1
        i += 1

    return windows

def fetch_with_retry(url, params, max_retries=MAX_RETRIES):
    for attempt in range(max_retries):
        try:
            r = requests.get(url, params=params, headers=HEADERS, timeout=30)

            if r.status_code == 200:
                return r.json()

            elif r.status_code == 429:
                wait = 8 * (2 ** attempt)
                print(f"[429] Rate limited. Waiting {wait}s...")
                time.sleep(wait)

            elif r.status_code in (502, 503):
                wait = 5 * (2 ** attempt)
                print(f"[{r.status_code}] Server error. Waiting {wait}s...")
                time.sleep(wait)

            else:
                print(f"[HTTP {r.status_code}] Unrecoverable for {url}")
                print("Params:", params)
                return None

        except requests.exceptions.RequestException as e:
            wait = 5 * (2 ** attempt)
            print(f"[Connection error] {e}. Waiting {wait}s...")
            time.sleep(wait)

    print(f"[FAILED] {url} after {max_retries} attempts.")
    return None

def extract_post_id_from_link_id(link_id):
    link_id = normalize_text(link_id)
    if link_id.startswith("t3_"):
        return link_id[3:]
    return link_id

def extract_parent_comment_id(parent_id):
    parent_id = normalize_text(parent_id)
    if parent_id.startswith("t1_"):
        return parent_id[3:]
    return None

def comment_exclusion_reason(c):
    author = normalize_text(c.get("author"))
    body = normalize_text(c.get("body"))
    distinguished = normalize_text(c.get("distinguished") or c.get("distinguished_by")).lower()
    stickied = bool(c.get("stickied", False))

    if author in {"", "[deleted]"}:
        return "blank_or_deleted_author"
    if AUTOMOD_RE.match(author):
        return "automoderator"
    if MODTEAM_RE.search(author):
        return "modteam_style_username"
    if distinguished == "moderator":
        return "distinguished_moderator"
    if stickied:
        return "stickied_comment"
    if body in {"", "[removed]", "[deleted]"}:
        return "removed_or_empty_body"

    return None

def post_flags(p):
    author = normalize_text(p.get("author"))
    title = normalize_text(p.get("title"))
    selftext = normalize_text(p.get("selftext"))
    distinguished = normalize_text(p.get("distinguished") or p.get("distinguished_by")).lower()
    stickied = bool(p.get("stickied", False))

    return {
        "post_author_blank_or_deleted": int(author in {"", "[deleted]"}),
        "post_author_automod": int(bool(AUTOMOD_RE.match(author))),
        "post_author_modteam_style": int(bool(MODTEAM_RE.search(author))),
        "post_distinguished_moderator": int(distinguished == "moderator"),
        "post_stickied": int(stickied),
        "post_title_blank": int(title == ""),
        "post_body_removed": int(selftext in {"[removed]", "[deleted]"}),
        "post_body_blank": int(selftext == ""),
        "post_text_available": int(selftext not in {"", "[removed]", "[deleted]"}),
    }

def add_time_columns(df, created_col="created_utc"):
    df = df.copy()
    if df.empty:
        return df
    df["date"] = pd.to_datetime(df[created_col], unit="s", utc=True)
    date_naive = df["date"].dt.tz_localize(None)
    df["week_start"] = date_naive.dt.to_period("W").apply(lambda r: r.start_time)
    df["year_week"] = df["week_start"].dt.strftime("%Y-W%U")
    df["parent_comment_id"] = df["parent_id"].apply(extract_parent_comment_id)
    return df

def normalize_for_template_check(text):
    text = normalize_text(text).lower()
    text = re.sub(r'https?://\S+', '<URL>', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def word_count(text):
    return len(normalize_text(text).split())

# =========================================================
# WEEK-BALANCED COMMENT COLLECTION
# =========================================================
def collect_clean_comments_for_window(subreddit, after_ts, before_ts, week_idx, week_label, target_clean):
    raw_rows = []
    clean_rows = []
    exclusion_rows = []
    seen_comment_ids = set()
    cursor = int(after_ts)

    pbar = tqdm(total=target_clean, desc=f"collect {week_label}", leave=False)

    while cursor <= before_ts:
        params = {
            "subreddit": subreddit,
            "after": int(cursor),
            "before": int(before_ts),
            "limit": COMMENT_PAGE_LIMIT,
            "sort": "asc",
        }

        data = fetch_with_retry(BASE_COMMENTS, params)
        if not data:
            break

        batch = data.get("data", [])
        if not batch:
            break

        unique_batch = []
        for c in batch:
            cid = c.get("id")
            if not cid or cid in seen_comment_ids:
                continue
            seen_comment_ids.add(cid)
            unique_batch.append(c)

        if not unique_batch:
            cursor += 1
            continue

        max_created = cursor

        for c in unique_batch:
            created_utc = int(c.get("created_utc", 0))
            max_created = max(max_created, created_utc)

            row = {
                "comment_id": c.get("id"),
                "post_id": extract_post_id_from_link_id(c.get("link_id")),
                "subreddit": c.get("subreddit"),
                "parent_id": c.get("parent_id"),
                "author": c.get("author"),
                "created_utc": created_utc,
                "text": c.get("body"),
                "distinguished": c.get("distinguished") or c.get("distinguished_by"),
                "stickied": bool(c.get("stickied", False)),
                "collection_week_idx": week_idx,
                "collection_week_label": week_label,
                "pulled_at_utc": PULLED_AT_UTC,
            }
            raw_rows.append(row)

            reason = comment_exclusion_reason(c)
            if reason is None:
                clean_rows.append(row.copy())
            else:
                exclusion_rows.append({
                    "comment_id": row["comment_id"],
                    "post_id": row["post_id"],
                    "author": row["author"],
                    "created_utc": row["created_utc"],
                    "reason": reason,
                    "body_preview": normalize_text(row["text"])[:220],
                    "collection_week_idx": week_idx,
                    "collection_week_label": week_label,
                    "pulled_at_utc": PULLED_AT_UTC,
                })

        pbar.n = min(len(clean_rows), target_clean)
        pbar.refresh()

        if len(clean_rows) >= target_clean:
            break

        cursor = max_created + 1
        time.sleep(SLEEP_SEC)

    pbar.close()

    raw_df = pd.DataFrame(raw_rows).drop_duplicates(subset=["comment_id"]).reset_index(drop=True)
    clean_df = pd.DataFrame(clean_rows).drop_duplicates(subset=["comment_id"]).reset_index(drop=True)
    excl_df = pd.DataFrame(exclusion_rows).drop_duplicates(subset=["comment_id"]).reset_index(drop=True)

    return raw_df, clean_df, excl_df

def remove_repeated_templates(comments_df):
    if comments_df.empty:
        empty_removed = pd.DataFrame(columns=list(comments_df.columns) + ["template_reason"])
        return comments_df.copy(), empty_removed

    tmp = comments_df.copy().sort_values(["author", "created_utc", "comment_id"]).reset_index(drop=True)
    tmp["template_norm"] = tmp["text"].apply(normalize_for_template_check)
    tmp["template_word_count"] = tmp["text"].apply(word_count)

    grp = (
        tmp.groupby(["author", "template_norm"])
           .agg(n_rows=("comment_id", "size"),
                n_posts=("post_id", "nunique"))
           .reset_index()
    )

    tmp = tmp.merge(grp, on=["author", "template_norm"], how="left")
    tmp["template_dup_rank"] = tmp.groupby(["author", "template_norm"]).cumcount()

    remove_mask = (
        (tmp["template_word_count"] >= MIN_TEMPLATE_WORDS) &
        (tmp["n_rows"] >= 2) &
        (tmp["n_posts"] >= 2) &
        (tmp["template_dup_rank"] >= 1)
    )

    removed_df = tmp[remove_mask].copy()
    removed_df["template_reason"] = "repeated_template_same_author"

    kept_df = tmp[~remove_mask].copy()

    drop_cols = ["template_norm", "template_word_count", "n_rows", "n_posts", "template_dup_rank"]
    kept_df = kept_df.drop(columns=drop_cols).reset_index(drop=True)
    removed_df = removed_df.drop(columns=drop_cols).reset_index(drop=True)

    return kept_df, removed_df

def collect_anchor_posts_across_window(subreddit, week_ranges, wanted_ids):
    found_posts = []
    seen_post_ids = set()

    with tqdm(total=len(wanted_ids), desc="anchor posts found") as pbar:
        for win in week_ranges:
            if len(seen_post_ids) >= len(wanted_ids):
                break

            cursor = int(win["after_ts"])
            before_ts = int(win["before_ts"])

            while cursor <= before_ts and len(seen_post_ids) < len(wanted_ids):
                params = {
                    "subreddit": subreddit,
                    "after": int(cursor),
                    "before": int(before_ts),
                    "limit": POST_PAGE_LIMIT,
                    "sort": "asc",
                }

                data = fetch_with_retry(BASE_POSTS, params)
                if not data:
                    break

                batch = data.get("data", [])
                if not batch:
                    break

                max_created = cursor

                for p in batch:
                    pid = normalize_text(p.get("id"))
                    created_utc = int(p.get("created_utc", 0))
                    max_created = max(max_created, created_utc)

                    if pid in wanted_ids and pid not in seen_post_ids:
                        row = {
                            "post_id": pid,
                            "subreddit": p.get("subreddit"),
                            "post_author": p.get("author"),
                            "post_created_utc": created_utc,
                            "post_title": p.get("title"),
                            "post_text": p.get("selftext"),
                            "pulled_at_utc": PULLED_AT_UTC,
                        }
                        row.update(post_flags(p))
                        found_posts.append(row)
                        seen_post_ids.add(pid)
                        pbar.update(1)

                cursor = max_created + 1
                time.sleep(SLEEP_SEC)

    return pd.DataFrame(found_posts).drop_duplicates(subset=["post_id"]).reset_index(drop=True)

def prune_broken_comment_links(comments_df, posts_df):
    comments_df = comments_df.copy().reset_index(drop=True)
    kept_post_ids = set(posts_df["post_id"].tolist())

    removed_total = 0

    while True:
        kept_comment_ids = set(comments_df["comment_id"].tolist())

        def parent_exists(parent_id):
            parent_id = normalize_text(parent_id)
            if parent_id.startswith("t3_"):
                return parent_id[3:] in kept_post_ids
            if parent_id.startswith("t1_"):
                return parent_id[3:] in kept_comment_ids
            return False

        keep_mask = comments_df["parent_id"].apply(parent_exists)
        removed_now = int((~keep_mask).sum())

        if removed_now == 0:
            return comments_df.reset_index(drop=True), removed_total

        removed_total += removed_now
        comments_df = comments_df[keep_mask].reset_index(drop=True)

def make_balanced_label_file(comments_df, per_week=LABEL_PER_WEEK):
    if comments_df.empty:
        return comments_df.copy()

    parts = []
    for yw, grp in comments_df.groupby("year_week", sort=True):
        n = min(per_week, len(grp))
        parts.append(grp.sample(n=n, random_state=42))

    out = pd.concat(parts, ignore_index=True)
    out = out.sort_values(["date", "comment_id"]).reset_index(drop=True)

    return out[[
        "comment_id", "post_id", "subreddit", "year_week", "author", "text"
    ]]

def make_overlap_file(comments_df, n=OVERLAP_LABEL_N):
    if comments_df.empty:
        return comments_df.copy()
    n = min(n, len(comments_df))
    out = comments_df.sample(n=n, random_state=7).sort_values(["date", "comment_id"]).reset_index(drop=True)
    return out[[
        "comment_id", "post_id", "subreddit", "year_week", "author", "text"
    ]]

# =========================================================
# RUN
# =========================================================
START_TS = to_ts(START_DATE)
END_TS = to_ts(END_DATE) + 86399
PULLED_AT_UTC = datetime.now(timezone.utc).isoformat()
week_ranges = build_week_ranges(START_DATE, END_DATE)

print(f"Subreddit      : r/{SUBREDDIT}")
print(f"Window         : {START_DATE} -> {END_DATE}")
print(f"Unix range     : {START_TS} -> {END_TS}")
print(f"Pulled at UTC  : {PULLED_AT_UTC}")
print(f"Week windows   : {len(week_ranges)}")
print(f"Target/week    : {TARGET_CLEAN_PER_WEEK}")

# Smoke test
smoke = fetch_with_retry(BASE_COMMENTS, {
    "subreddit": SUBREDDIT,
    "after": START_TS,
    "before": min(START_TS + 86400, END_TS),
    "limit": 5,
    "sort": "asc",
})
if smoke is None:
    raise RuntimeError("Comment endpoint smoke test failed.")
print(f"Comment endpoint smoke test succeeded. Returned {len(smoke.get('data', []))} rows.\n")

# 1) Collect comments week by week
raw_parts = []
clean_parts = []
excl_parts = []

for win in week_ranges:
    raw_df, clean_df, excl_df = collect_clean_comments_for_window(
        SUBREDDIT,
        win["after_ts"],
        win["before_ts"],
        win["week_idx"],
        win["week_label"],
        TARGET_CLEAN_PER_WEEK,
    )
    raw_parts.append(raw_df)
    clean_parts.append(clean_df)
    excl_parts.append(excl_df)

comments_raw_df = pd.concat(raw_parts, ignore_index=True) if raw_parts else pd.DataFrame()
comments_clean_df = pd.concat(clean_parts, ignore_index=True) if clean_parts else pd.DataFrame()
comment_exclusions_df = pd.concat(excl_parts, ignore_index=True) if excl_parts else pd.DataFrame()

comments_raw_df = comments_raw_df.drop_duplicates(subset=["comment_id"]).reset_index(drop=True)
comments_clean_df = comments_clean_df.drop_duplicates(subset=["comment_id"]).reset_index(drop=True)
comment_exclusions_df = comment_exclusions_df.drop_duplicates(subset=["comment_id"]).reset_index(drop=True)

print("Raw comments collected   :", len(comments_raw_df))
print("Clean before templates   :", len(comments_clean_df))
print("Excluded moderation/sys  :", len(comment_exclusions_df))

# 2) Add time/reply columns
comments_clean_df = add_time_columns(comments_clean_df)

# 3) Remove repeated same-author boilerplate
comments_retained_df, template_removed_df = remove_repeated_templates(comments_clean_df)

print("Removed repeated templates:", len(template_removed_df))
print("Clean after templates     :", len(comments_retained_df))

# 4) Fetch anchor posts only for retained comments
wanted_post_ids = set(comments_retained_df["post_id"].dropna().astype(str).tolist())
posts_anchor_df = collect_anchor_posts_across_window(SUBREDDIT, week_ranges, wanted_post_ids)

print("Wanted anchor posts       :", len(wanted_post_ids))
print("Found anchor posts        :", len(posts_anchor_df))

# 5) Prune comments with broken parent links after final retention
comments_final_df, pruned_n = prune_broken_comment_links(comments_retained_df, posts_anchor_df)
comments_final_df = add_time_columns(comments_final_df)

final_comment_ids = set(comments_final_df["comment_id"].tolist())
comments_final_df["has_parent_in_window"] = comments_final_df["parent_comment_id"].isin(final_comment_ids)
comments_final_df["is_direct_reply"] = comments_final_df["parent_id"].astype(str).str.startswith("t3_")
comments_final_df["parent_post_found"] = comments_final_df["post_id"].isin(set(posts_anchor_df["post_id"].tolist()))

print("Pruned broken-link comments:", pruned_n)
print("Final clean comments        :", len(comments_final_df))

# 6) Balanced labeling outputs
to_label_df = make_balanced_label_file(comments_final_df, per_week=LABEL_PER_WEEK)
overlap_label_df = make_overlap_file(comments_final_df, n=OVERLAP_LABEL_N)

# 7) Weekly summary
def count_by_week(df, label_col="collection_week_label", value_name="count"):
    if df.empty or label_col not in df.columns:
        return pd.DataFrame(columns=[label_col, value_name])
    return df.groupby(label_col).size().reset_index(name=value_name)

weekly_summary_df = pd.DataFrame({"collection_week_label": [w["week_label"] for w in week_ranges]})

weekly_summary_df = weekly_summary_df.merge(
    count_by_week(comments_raw_df, value_name="raw_comments"),
    on="collection_week_label", how="left"
)
weekly_summary_df = weekly_summary_df.merge(
    count_by_week(comments_clean_df, value_name="clean_before_templates"),
    on="collection_week_label", how="left"
)
weekly_summary_df = weekly_summary_df.merge(
    count_by_week(comment_exclusions_df, value_name="excluded_mod_sys"),
    on="collection_week_label", how="left"
)
weekly_summary_df = weekly_summary_df.merge(
    count_by_week(template_removed_df, value_name="removed_templates"),
    on="collection_week_label", how="left"
)
weekly_summary_df = weekly_summary_df.merge(
    count_by_week(comments_final_df, value_name="final_clean_comments"),
    on="collection_week_label", how="left"
)

weekly_summary_df = weekly_summary_df.fillna(0)

# 8) Save outputs
TAG = f"{START_DATE.replace('-', '')}_{END_DATE.replace('-', '')}_weekbalanced"

comments_raw_out        = f"{SUBREDDIT}_comments_raw_{TAG}.csv"
comments_clean_out      = f"{SUBREDDIT}_comments_clean_final_{TAG}.csv"
comments_excl_out       = f"{SUBREDDIT}_comment_exclusions_{TAG}.csv"
comments_template_out   = f"{SUBREDDIT}_comment_templates_removed_{TAG}.csv"
posts_anchor_out        = f"{SUBREDDIT}_anchor_posts_{TAG}.csv"
weekly_summary_out      = f"{SUBREDDIT}_weekly_summary_{TAG}.csv"
to_label_out            = f"{SUBREDDIT}_to_label_balanced_{TAG}.csv"
overlap_label_out       = f"{SUBREDDIT}_to_label_overlap_{TAG}.csv"

comments_raw_df.to_csv(comments_raw_out, index=False)
comments_final_df.to_csv(comments_clean_out, index=False)
comment_exclusions_df.to_csv(comments_excl_out, index=False)
template_removed_df.to_csv(comments_template_out, index=False)
posts_anchor_df.to_csv(posts_anchor_out, index=False)
weekly_summary_df.to_csv(weekly_summary_out, index=False)
to_label_df.to_csv(to_label_out, index=False)
overlap_label_df.to_csv(overlap_label_out, index=False)

# 9) Final summary
overall_summary_df = pd.DataFrame([
    ["subreddit", SUBREDDIT],
    ["window_start", START_DATE],
    ["window_end", END_DATE],
    ["pulled_at_utc", PULLED_AT_UTC],
    ["num_week_windows", len(week_ranges)],
    ["target_clean_per_week", TARGET_CLEAN_PER_WEEK],
    ["raw_comments", len(comments_raw_df)],
    ["clean_before_templates", len(comments_clean_df)],
    ["excluded_mod_system", len(comment_exclusions_df)],
    ["removed_repeated_templates", len(template_removed_df)],
    ["final_clean_comments", len(comments_final_df)],
    ["anchor_posts_found", len(posts_anchor_df)],
    ["unique_comment_authors", comments_final_df["author"].nunique() if not comments_final_df.empty else 0],
    ["unique_posts_in_final", comments_final_df["post_id"].nunique() if not comments_final_df.empty else 0],
    ["weeks_covered_final", comments_final_df["year_week"].nunique() if not comments_final_df.empty else 0],
    ["to_label_rows", len(to_label_df)],
    ["overlap_label_rows", len(overlap_label_df)],
], columns=["metric", "value"])

reason_counts_df = (
    comment_exclusions_df["reason"].value_counts(dropna=False)
    .rename_axis("reason")
    .reset_index(name="count")
    if not comment_exclusions_df.empty else pd.DataFrame(columns=["reason", "count"])
)

print("\n=== OVERALL SUMMARY ===")
print(overall_summary_df.to_string(index=False))

print("\n=== MOD/SYSTEM EXCLUSION REASONS ===")
print(reason_counts_df.to_string(index=False) if not reason_counts_df.empty else "No exclusions.")

print("\n=== FINAL CLEAN COMMENT DATE RANGE ===")
if not comments_final_df.empty:
    print("Min:", comments_final_df["date"].min())
    print("Max:", comments_final_df["date"].max())

print("\n=== WEEKLY COVERAGE ===")
print(weekly_summary_df.to_string(index=False))

print("\nSaved files:")
print(" -", comments_raw_out)
print(" -", comments_clean_out)
print(" -", comments_excl_out)
print(" -", comments_template_out)
print(" -", posts_anchor_out)
print(" -", weekly_summary_out)
print(" -", to_label_out)
print(" -", overlap_label_out)

# 10) Optional Colab display
try:
    from google.colab import data_table
    from IPython.display import display, Markdown
    data_table.enable_dataframe_formatter()

    display(Markdown("## Overall Summary"))
    display(overall_summary_df)

    display(Markdown("## Weekly Summary"))
    display(weekly_summary_df)

    display(Markdown("## Exclusion Reasons"))
    display(reason_counts_df)

    display(Markdown("## Final Clean Comments Preview"))
    display(comments_final_df[[
        "comment_id", "post_id", "author", "date", "year_week",
        "parent_id", "parent_comment_id", "has_parent_in_window",
        "is_direct_reply", "text"
    ]].head(50))

    display(Markdown("## Removed Repeated Templates Preview"))
    if not template_removed_df.empty:
        display(template_removed_df[[
            "comment_id", "post_id", "author", "date", "year_week",
            "template_reason", "text"
        ]].head(50))

    display(Markdown("## Anchor Posts Preview"))
    if not posts_anchor_df.empty:
        display(posts_anchor_df[[
            "post_id", "post_author", "post_created_utc", "post_title",
            "post_text_available", "post_body_removed", "post_stickied"
        ]].head(50))

except Exception as e:
    print("\nInteractive Colab display unavailable:", e)

Subreddit      : r/askscience
Window         : 2025-10-06 -> 2025-12-28
Unix range     : 1759708800 -> 1766966399
Pulled at UTC  : 2026-04-07T03:14:42.465793+00:00
Week windows   : 12
Target/week    : 250
Comment endpoint smoke test succeeded. Returned 5 rows.

collect W01_2025-10-06_to_2025-10-12:   0%|          | 0/250 [00:00<?, ?it/s]

collect W02_2025-10-13_to_2025-10-19:   0%|          | 0/250 [00:00<?, ?it/s]

collect W03_2025-10-20_to_2025-10-26:   0%|          | 0/250 [00:00<?, ?it/s]

collect W04_2025-10-27_to_2025-11-02:   0%|          | 0/250 [00:00<?, ?it/s]

collect W05_2025-11-03_to_2025-11-09:   0%|          | 0/250 [00:00<?, ?it/s]

collect W06_2025-11-10_to_2025-11-16:   0%|          | 0/250 [00:00<?, ?it/s]

collect W07_2025-11-17_to_2025-11-23:   0%|          | 0/250 [00:00<?, ?it/s]

collect W08_2025-11-24_to_2025-11-30:   0%|          | 0/250 [00:00<?, ?it/s]

collect W09_2025-12-01_to_2025-12-07:   0%|          | 0/250 [00:00<?, ?it/s]

collect W10_2025-12-08_to_2025-12-14:   0%|          | 0/250 [00:00<?, ?it/s]

collect W11_2025-12-15_to_2025-12-21:   0%|          | 0/250 [00:00<?, ?it/s]

collect W12_2025-12-22_to_2025-12-28:   0%|          | 0/250 [00:00<?, ?it/s]

Raw comments collected   : 6600
Clean before templates   : 3313
Excluded moderation/sys  : 3287
Removed repeated templates: 2
Clean after templates     : 3311

anchor posts found:   0%|          | 0/218 [00:00<?, ?it/s]

Wanted anchor posts       : 218
Found anchor posts        : 190
Pruned broken-link comments: 770
Final clean comments        : 2541

=== OVERALL SUMMARY ===
                    metric                            value
                 subreddit                       askscience
              window_start                       2025-10-06
                window_end                       2025-12-28
             pulled_at_utc 2026-04-07T03:14:42.465793+00:00
          num_week_windows                               12
     target_clean_per_week                              250
              raw_comments                             6600
    clean_before_templates                             3313
       excluded_mod_system                             3287
removed_repeated_templates                                2
      final_clean_comments                             2541
        anchor_posts_found                              190
    unique_comment_authors                             1668
     unique_posts_in_final                              153
       weeks_covered_final                               12
             to_label_rows                              300
        overlap_label_rows                              100

=== MOD/SYSTEM EXCLUSION REASONS ===
                 reason  count
blank_or_deleted_author   1932
          automoderator   1054
 modteam_style_username    295
distinguished_moderator      6

=== FINAL CLEAN COMMENT DATE RANGE ===
Min: 2025-10-06 05:15:55+00:00
Max: 2025-12-24 17:28:11+00:00

=== WEEKLY COVERAGE ===
       collection_week_label  raw_comments  clean_before_templates  excluded_mod_sys  removed_templates  final_clean_comments
W01_2025-10-06_to_2025-10-12           500                     250               250                2.0                   203
W02_2025-10-13_to_2025-10-19           500                     263               237                0.0                   180
W03_2025-10-20_to_2025-10-26           600                     288               312                0.0                   206
W04_2025-10-27_to_2025-11-02           500                     291               209                0.0                   240
W05_2025-11-03_to_2025-11-09           600                     302               298                0.0                   252
W06_2025-11-10_to_2025-11-16           500                     262               238                0.0                   236
W07_2025-11-17_to_2025-11-23           500                     264               236                0.0                   222
W08_2025-11-24_to_2025-11-30           500                     271               229                0.0                   222
W09_2025-12-01_to_2025-12-07           700                     261               439                0.0                   225
W10_2025-12-08_to_2025-12-14           700                     266               434                0.0                   149
W11_2025-12-15_to_2025-12-21           500                     308               192                0.0                   246
W12_2025-12-22_to_2025-12-28           500                     287               213                0.0                   160

Saved files:
 - askscience_comments_raw_20251006_20251228_weekbalanced.csv
 - askscience_comments_clean_final_20251006_20251228_weekbalanced.csv
 - askscience_comment_exclusions_20251006_20251228_weekbalanced.csv
 - askscience_comment_templates_removed_20251006_20251228_weekbalanced.csv
 - askscience_anchor_posts_20251006_20251228_weekbalanced.csv
 - askscience_weekly_summary_20251006_20251228_weekbalanced.csv
 - askscience_to_label_balanced_20251006_20251228_weekbalanced.csv
 - askscience_to_label_overlap_20251006_20251228_weekbalanced.csv

## Overall Summary

                        metric                             value
0                    subreddit                        askscience
1                 window_start                        2025-10-06
2                   window_end                        2025-12-28
3                pulled_at_utc  2026-04-07T03:14:42.465793+00:00
4             num_week_windows                                12
5        target_clean_per_week                               250
6                 raw_comments                              6600
7       clean_before_templates                              3313
8          excluded_mod_system                              3287
9   removed_repeated_templates                                 2
10        final_clean_comments                              2541
11          anchor_posts_found                               190
12      unique_comment_authors                              1668
13       unique_posts_in_final                               153
14         weeks_covered_final                                12
15               to_label_rows                               300
16          overlap_label_rows                               100

## Weekly Summary

,collection_week_label,raw_comments,clean_before_templates,excluded_mod_sys,removed_templates,final_clean_comments
0,W01_2025-10-06_to_2025-10-12,500,250,250,2.0,203
1,W02_2025-10-13_to_2025-10-19,500,263,237,0.0,180
2,W03_2025-10-20_to_2025-10-26,600,288,312,0.0,206
3,W04_2025-10-27_to_2025-11-02,500,291,209,0.0,240
4,W05_2025-11-03_to_2025-11-09,600,302,298,0.0,252
5,W06_2025-11-10_to_2025-11-16,500,262,238,0.0,236
6,W07_2025-11-17_to_2025-11-23,500,264,236,0.0,222
7,W08_2025-11-24_to_2025-11-30,500,271,229,0.0,222
8,W09_2025-12-01_to_2025-12-07,700,261,439,0.0,225
9,W10_2025-12-08_to_2025-12-14,700,266,434,0.0,149
10,W11_2025-12-15_to_2025-12-21,500,308,192,0.0,246
11,W12_2025-12-22_to_2025-12-28,500,287,213,0.0,160

## Exclusion Reasons

                    reason  count
0  blank_or_deleted_author   1932
1            automoderator   1054
2   modteam_style_username    295
3  distinguished_moderator      6

## Final Clean Comments Preview

,comment_id,post_id,author,date,year_week,parent_id,parent_comment_id,has_parent_in_window,is_direct_reply,text
0,nrrcpjy,1pb9jq8,--Chug--,2025-12-01 19:25:23+00:00,2025-W48,t1_nrqnbic,nrqnbic,True,False,I'd say they're still planets just not major o...
1,njpquxv,1o7a3uc,-Metacelsus-,2025-10-16 00:18:41+00:00,2025-W41,t1_njoras5,njoras5,True,False,> yet if we give it to certain primates it cou...
2,nu55nbz,1pmpuzp,-Metacelsus-,2025-12-15 12:04:57+00:00,2025-W50,t1_nu4ygzy,nu4ygzy,True,False,> This bounces light through the crystalline l...
3,nicxdqm,1nzk1tr,-dantes-,2025-10-08 02:41:01+00:00,2025-W40,t1_ni4ivj4,ni4ivj4,True,False,I heard somewhere that creatures that evolved ...
4,njmxjfw,1o4ves5,095179005,2025-10-15 15:30:35+00:00,2025-W41,t3_1o4ves5,None,False,True,"Aside from the wonderful detailed answers,\n\n..."
5,nkg7g72,1oag8fc,095179005,2025-10-20 08:57:52+00:00,2025-W42,t3_1oag8fc,None,False,True,An addition to the explanations and reasons ot...
6,nkulx98,1od93jq,095179005,2025-10-22 21:18:33+00:00,2025-W42,t1_nktkm9o,nktkm9o,True,False,This response about how cells know where they ...
7,nqh9yef,1p4o0yp,095179005,2025-11-24 04:35:45+00:00,2025-W47,t3_1p4o0yp,None,False,True,Evolution is descent with modification.\n\nAll...
8,nrn10rj,1pareq7,095179005,2025-12-01 01:48:25+00:00,2025-W48,t3_1pareq7,None,False,True,So the paper states that out of 160 known spec...
9,nvp0ssh,1pu20gm,0oSlytho0,2025-12-24 09:54:24+00:00,2025-W51,t1_nvmo8jm,nvmo8jm,True,False,"That can also be a happy coincident, and a sli..."
10,nuart73,1pn3xej,0x14f,2025-12-16 07:41:44+00:00,2025-W50,t1_nu8z0d4,nu8z0d4,True,False,\> does that mean light goes ever so slightly ...
11,nkwi4yp,1o5jphw,15MinuteUpload,2025-10-23 04:14:14+00:00,2025-W42,t1_njfcfh0,njfcfh0,True,False,How high can you go with bone conduction out o...
12,nn2srlu,1on689t,1K_Games,2025-11-04 16:23:56+00:00,2025-W44,t1_nmwmcou,nmwmcou,True,False,Purring to calm themselves is only one thing t...
13,nogd19d,1otx6m8,1LuckyTexan,2025-11-12 13:43:03+00:00,2025-W45,t1_nog705j,nog705j,True,False,I think I read once that a Zoo can lose their ...
14,nlo2v9x,1ogqo80,1XRobot,2025-10-27 16:00:20+00:00,2025-W43,t1_nlnsbyu,nlnsbyu,True,False,Someone who just so happens to love typing em ...
15,nmxwhni,1on689t,1nput0utput,2025-11-03 20:30:44+00:00,2025-W44,t3_1on689t,None,False,True,The [Twenty Thousand Hertz podcast](https://ww...
16,nlo0pce,1oh741p,2028Freedom,2025-10-27 15:49:44+00:00,2025-W43,t1_nlnhuro,nlnhuro,True,False,how many vents/volcanoes would have existed? O...
17,nvmnapn,1pu6h0y,2401tim,2025-12-23 23:22:29+00:00,2025-W51,t3_1pu6h0y,None,False,True,https://doi.org/10.1016/j.cois.2019.01.005\n\n...
18,nu5xal0,1pmpuzp,2K11SS,2025-12-15 14:57:18+00:00,2025-W50,t1_nu55nbz,nu55nbz,True,False,It's been a while since I've worked on ophthal...
19,nu6g7ev,1pmpuzp,2K11SS,2025-12-15 16:30:56+00:00,2025-W50,t1_nu6bn9s,nu6bn9s,True,False,Most auto-refractors will be able to get spher...
20,nu8himo,1pmpuzp,2K11SS,2025-12-15 22:31:57+00:00,2025-W50,t1_nu6l69e,nu6l69e,True,False,Optic nerve/disc drusen is seen in the back of...
21,nqivj3o,1p51yua,2legittoquit,2025-11-24 13:13:19+00:00,2025-W47,t3_1p51yua,None,False,True,Synaptic connections are different for them. ...
22,nodbgmb,1otx6m8,314159265358979326,2025-11-11 23:48:28+00:00,2025-W45,t1_nod6e6s,nod6e6s,True,False,Vitamin C in particular is extremely widesprea...
23,nrs210t,1pbafk5,314159265358979326,2025-12-01 21:34:34+00:00,2025-W48,t1_nrs14zn,nrs14zn,True,False,Water actually works double duty for putting o...
24,nvmmftb,1pu20gm,314159265358979326,2025-12-23 23:17:24+00:00,2025-W51,t1_nvm76is,nvm76is,True,False,Is there a cost to protecting the snake itself...
25,nkspwld,1oc9h4r,3armsOrNoArms,2025-10-22 15:51:59+00:00,2025-W42,t1_nkp33xt,nkp33xt,True,False,"With current CRISPR delivery methods, how much..."
26,nvkxgb7,1pstd4o,444cml,2025-12-23 17:59:24+00:00,2025-W51,t3_1pstd4o,None,False,True,What you stumbled on was likely a meme or pop ...
27,nphddo8,1ozpcir,4tehlulzez,2025-11-18 12:34:12+00:00,2025-W46,t1_npgrn66,npgrn66,True,False,I know it’s just astromonomonology but it amaz...
28,no72bo4,1otq9qr,588-2300_empire,2025-11-10 23:54:29+00:00,2025-W45,t3_1otq9qr,None,False,True,How far are we from deepfake video that is ind...
29,nuajdr3,1pn06e8,5minArgument,2025-12-16 06:23:24+00:00,2025-W50,t1_nu832fd,nu832fd,True,False,Does pose an fair question tho. Relativity bei...
30,nuc0foy,1pn06e8,5minArgument,2025-12-16 13:56:16+00:00,2025-W50,t1_nuaqmt3,nuaqmt3,True,False,"Completely understood. However, we can't say w..."
31,nu83gxg,1pn3xej,5p0ng3b0b,2025-12-15 21:20:19+00:00,2025-W50,t3_1pn3xej,None,False,True,Let's say you do this measurement when your sp...
32,nvhud82,1pstd4o,6_inches_of_travel,2025-12-23 05:00:26+00:00,2025-W51,t3_1pstd4o,None,False,True,"In the way you've stated it, It's just a simpl..."
33,nubnfo9,1pnj8n3,831pm,2025-12-16 12:33:50+00:00,2025-W50,t3_1pnj8n3,None,False,True,As someone who grew up wanting to be a paleont...
34,ni57epx,1nzk1tr,A3thereal,2025-10-06 21:55:29+00:00,2025-W40,t1_ni4wr82,ni4wr82,True,False,A few generations? Not much. Evolution doesnt...
35,npfx9lm,1ozj9lu,ADDeviant-again,2025-11-18 04:37:50+00:00,2025-W46,t1_npfk20c,npfk20c,True,False,"Also, not all mosquitoes drink, nectar a lot o..."
36,njbku9n,1o5jphw,ALifeWithoutBreath,2025-10-13 19:03:11+00:00,2025-W41,t1_njb6fb8,njb6fb8,True,False,"So higher frequencies travel under water, some..."
37,njcl76n,1o5jphw,ALifeWithoutBreath,2025-10-13 22:09:42+00:00,2025-W41,t1_njcc3e7,njcc3e7,True,False,"Actually, I have been coming across sources th..."
38,njd7wxf,1o5jphw,ALifeWithoutBreath,2025-10-14 00:22:29+00:00,2025-W41,t1_njcpbyn,njcpbyn,True,False,"Oh, well. And here I was hoping that it's just..."
39,nuatohw,1pnj8n3,AMRossGX,2025-12-16 07:59:50+00:00,2025-W50,t1_nuajc5f,nuajc5f,True,False,"Great image, thanks for posting it, very inter..."
40,nj7ekd0,1o2osvl,Aaron_Pitterman,2025-10-13 02:01:53+00:00,2025-W41,t3_1o2osvl,None,False,True,1. Pretty sure your body only absorbs calories...
41,nqr2jzv,1p6dr0q,AbleKaleidoscope877,2025-11-25 19:06:58+00:00,2025-W47,t3_1p6dr0q,None,False,True,Sutures help stop bleeding by forcing the edge...
42,nlnj3nt,1ogqo80,Able_Ambition_6863,2025-10-27 14:21:38+00:00,2025-W43,t1_nlnf3qv,nlnf3qv,True,False,One day I should read the original studies. I ...
43,nmy3zxp,1on689t,AboveHeavenImmortal,2025-11-03 21:06:39+00:00,2025-W44,t1_nmxk019,nmxk019,True,False,Yeah you don't even realize it... You blink hu...
44,ni8jsy7,1nzk1tr,Acoke94,2025-10-07 12:43:47+00:00,2025-W40,t1_ni70ydi,ni70ydi,True,False,It’s a pretty fascinating Wikipedia read. I wo...
45,nrv07in,1p9zjqj,Adventurous-Ad3393,2025-12-02 09:46:50+00:00,2025-W48,t3_1p9zjqj,None,False,True,You’re an engineer. You need to move energy in...
46,nmvkiw6,1okgqg2,AdventurousLife3226,2025-11-03 13:35:21+00:00,2025-W44,t3_1okgqg2,None,False,True,"Yes, in fact many propeller planes have broken..."
47,no7p1xk,1otq9qr,Adventurous_Side2706,2025-11-11 02:10:25+00:00,2025-W45,t3_1otq9qr,None,False,True,How viable is it to train a joint embedding sp...
48,nofl19r,1ov0wxc,Adventurous_Side2706,2025-11-12 10:04:24+00:00,2025-W45,t3_1ov0wxc,None,False,True,Do you think bioluminescence represents a conv...
49,nohnuup,1ov7gf1,Adventurous_Side2706,2025-11-12 17:43:10+00:00,2025-W45,t3_1ov7gf1,None,False,True,How do engineers choose or create materials fo...

## Removed Repeated Templates Preview

,comment_id,post_id,author,date,year_week,template_reason,text
0,ni0raik,1nzaihs,stars9r9in9the9past,2025-10-06 05:19:22+00:00,2025-W40,repeated_template_same_author,I was look at the upcoming 7-day for the week ...
1,ni0rhku,1nzajlx,stars9r9in9the9past,2025-10-06 05:21:06+00:00,2025-W40,repeated_template_same_author,I was look at the upcoming 7-day for the week ...

## Anchor Posts Preview

,post_id,post_author,post_created_utc,post_title,post_text_available,post_body_removed,post_stickied
0,1nz6p4c,AirportStraight8079,1759716043,Do the strongest earthquake permanently rise g...,1,0,0
1,1nzagds,stars9r9in9the9past,1759727747,Basics to Meteorology,0,1,0
2,1nzk1tr,Derole,1759759652,Why are we not crushed by the air above us?,1,0,0
3,1o09tql,disconcertedad1023,1759828571,Why are airplane windows not as large as helic...,0,0,0
4,1o0m74r,L1fel0ver2002,1759860076,Why are stars/planets only spherical?,0,1,0
5,1o0ptjd,Electronic_Click_470,1759867937,Could information travel faster than light thr...,0,1,0
6,1o1wkod,LikesBlueberriesALot,1759983578,"It seems like birds, rabbits, squirrels etc. w...",0,0,0
7,1o1zcqf,mooman996,1759993807,Is Earth getting smoother over time?,1,0,0
8,1o250a0,jemmylegs,1760014088,Why do we need red blood cells?,1,0,0
9,1o25xvb,AkelaAnda,1760016501,"if anything with mass curves spacetime, even i...",1,0,0
10,1o27g5c,efficiens,1760020184,Does an applied force always deform or move an...,1,0,0
11,1o2mewr,ynfive,1760055688,"Do galaxies in groups, clusters, or the whole ...",1,0,0
12,1o2osvl,Possible_Art2189,1760062559,"If a piece of gum is, say, 5 calories, does th...",0,0,0
13,1o3fczz,shtty_analogy,1760136109,How do they give mice cancer to test on?,0,0,0
14,1o3h61j,CelluloseNitrate,1760140997,Why do some flowers want only a specific polli...,1,0,0
15,1o3roj9,qatanah,1760176674,What worse thing earthquake are we expecting i...,1,0,0
16,1o3w91f,Prestigious_Emu6039,1760190898,How can different laws apply to tiny things?,1,0,0
17,1o4op8v,Sure-Initiative685,1760274689,How does U-Pb Isotope dating work?,1,0,0
18,1o4segt,Neither_Warthog_3843,1760283850,What is the Martian night sky like?,0,0,0
19,1o4ves5,mrphysh,1760290775,COVID vaccinations are genetics based. How is...,1,0,0
20,1o5bows,SimonVanc,1760334911,"Do people in a coma have a distinct sleep/""wak...",0,0,0
21,1o5eygx,Brilliant_Minimum312,1760347313,Can multiple fault lines be connected to a sin...,1,0,0
22,1o5jphw,ALifeWithoutBreath,1760362072,How It Possible That We Can Hear Higher Freque...,0,0,0
23,1o6pvkf,CiaranONeill381,1760471689,How long would have passed on Earth if I were ...,0,1,0
24,1o6z2ss,JackofScarlets,1760494995,Why are gemstones so small?,1,0,0
25,1o7a3uc,Significant_Bet3409,1760532618,Are humans disease carriers for any animal pop...,1,0,0
26,1o7bt06,AutoModerator,1760536831,"Ask Anything Wednesday - Engineering, Mathemat...",1,0,0
27,1o7hqqi,inspiredfighter,1760550058,What is the likehood of a virus finding anothe...,1,0,0
28,1o7j9v1,imaris_help,1760553461,How do the linear ends of chromosomes not trou...,1,0,0
29,1o93no1,Hawtdoq,1760713211,how do we have a solid explanation of how old ...,1,0,0
30,1o94oak,Lysania701,1760715477,What diseases are close to having a cure in th...,0,0,0
31,1o97k43,hgwelz,1760722008,How does a data center in a desert create doub...,1,0,0
32,1o9p3qy,EnvironmentalWalk920,1760771127,How does the Central Limit Theorem not contrad...,1,0,0
33,1oa7ru6,SparkyGirly,1760822475,Why do some volcanoes go full-on firecracker m...,0,0,0
34,1oag8fc,CrimsonDew125769,1760847150,Why is each amino acid encoded by a triplet of...,0,0,0
35,1oajz8a,MedicineMean5503,1760860842,Why can’t we weaken live viruses like the comm...,1,0,0
36,1ob6dtn,Bagelman263,1760921740,Did other species in genus homo have permanent...,1,0,0
37,1obtutr,EatBeansAndMeat,1760994443,Why is there a huge ice continent in the south...,0,0,0
38,1oc18hp,kempff,1761013866,Do we know why Type O blood is prevalent in th...,1,0,0
39,1oc1pgp,butidontthink,1761015231,Is there a difference in the internal structur...,1,0,0
40,1oc5qb7,EffectiveMixture2024,1761028666,Are filtration devices installed in the water ...,1,0,0
41,1oc7bet,AskScienceModerator,1761034876,AskScience AMA Series: We're experts working o...,1,0,0
42,1oc9h4r,toggler_H,1761043041,Can Gene Editing be done on grown adults?,1,0,0
43,1od0145,EnoughBar1159,1761111712,What is the vertical velocity of an object at ...,0,1,0
44,1od93jq,AutoModerator,1761141657,"Ask Anything Wednesday - Biology, Chemistry, N...",1,0,0
45,1oduk1a,Flapjack_Ace,1761195667,"If a population is around 3% Neanderthal, does...",1,0,0
46,1odxege,AskScienceModerator,1761206458,AskScience AMA Series: I oversee the Smithsoni...,1,0,0
47,1odzs60,RealLars_vS,1761215598,"If cows produce greenhouse emissions, where do...",1,0,0
48,1oe1yxq,Standard-Assistant27,1761222591,Do negative calorie foods exist?,1,0,0
49,1oe3pdz,michaelquinlan,1761227197,Why is blood pressure measured in mmHg and not...,1,0,0